name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install package (editable) + dev deps
        run: |
          pip install -e .[dev]

      - name: Lint
        run: |
          ruff --version
          ruff check .
          black --check .

      - name: Tests
        run: pytest -q

      - name: Generate demo reports
        run: |
          if [ -f Makefile ]; then make demo || true; fi
          mkdir -p reports || true

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ser-snapshot-diff-reports-${{ matrix.python-version }}
          path: reports
          if-no-files-found: warn
          retention-days: 14
          compression-level: 6

  release-binaries:
    name: Release single-file binaries
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ""
            asset_name: ser-diff-linux
          - os: macos-latest
            extension: ""
            asset_name: ser-diff-macos
          - os: windows-latest
            extension: ".exe"
            asset_name: ser-diff-windows.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller .

      - name: Build single-file binary
        run: |
          pyinstaller --name ser-diff --onefile --console -p src -m serdiff.cli
        shell: bash

      - name: Rename artifact
        run: |
          mkdir -p dist
          mv dist/ser-diff${{ matrix.extension }} dist/${{ matrix.asset_name }}
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.asset_name }}
