name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[dev]
      - name: Ruff
        run: python -m ruff check src/serdiff tests
      - name: Black
        run: python -m black --check src/serdiff tests
      - name: Pytest
        run: python -m pytest
      - name: Demo artifacts
        run: make demo
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: demo-reports-${{ matrix.python-version }}
          path: reports/
