name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  tests:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -e .[dev]

      - name: Run linters
        run: |
          ruff check .
          black --check .

      - name: Run tests
        run: pytest -q

  build:
    name: Build ${{ matrix.os }}
    needs: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] pyinstaller

      - name: Preflight: verify GUI script path + guard against stale references
        shell: bash
        run: |
          set -e
          echo "Workspace:" && pwd
          echo "Searching for GUI script..."
          test -f "src/serdiff/gui_runner.py" || { echo "::error::Missing src/serdiff/gui_runner.py"; exit 1; }
          echo "OK: src/serdiff/gui_runner.py present"
          echo "Checking for stale bad path..."
          if git grep -n "pyinstaller/src/serdiff/gui_runner.py" -- . ; then
            echo "::error::Stale path 'pyinstaller/src/serdiff/gui_runner.py' found above. Fix references before releasing."
            exit 1
          fi
          echo "No stale path found."

      - name: Build GUI binary
        id: build_gui
        shell: bash
        run: |
          set -e
          mkdir -p upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed -n "SER-Diff" src/serdiff/gui_runner.py
            cp dist/SER-Diff.exe upload/
            printf "Double-click SER-Diff.exe\nPick BEFORE/AFTER XML\n" > upload/README_RUN_ME.txt
            powershell -command "Compress-Archive -Path upload\* -DestinationPath SER-Diff-Windows.zip"
            echo "archive=SER-Diff-Windows.zip" >> "$GITHUB_OUTPUT"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --onefile --windowed -n "SER-Diff" src/serdiff/gui_runner.py
            cp -R "dist/SER-Diff.app" upload/
            printf "Open SER-Diff.app (Gatekeeper may prompt)\n" > upload/README_RUN_ME.txt
            (cd upload && zip -r ../SER-Diff-macOS.zip .)
            echo "archive=SER-Diff-macOS.zip" >> "$GITHUB_OUTPUT"
          else
            pyinstaller --onefile --windowed -n "ser-diff-gui" src/serdiff/gui_runner.py
            cp dist/ser-diff-gui upload/
            printf "./ser-diff-gui\n" > upload/README_RUN_ME.txt
            (cd upload && zip -r ../SER-Diff-Linux.zip .)
            echo "archive=SER-Diff-Linux.zip" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build_gui.outputs.archive }}
