name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  tests:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -e .[dev]

      - name: Run linters
        run: |
          ruff check .
          black --check .

      - name: Run tests
        run: pytest -q

  build:
    name: Build ${{ matrix.os }}
    needs: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] pyinstaller

      - name: Preflight: verify entrypoint scripts & guard stale refs
        shell: bash
        run: |
          set -e
          test -f "src/serdiff/gui_runner.py" || { echo "::error::Missing src/serdiff/gui_runner.py"; exit 1; }
          test -f "src/serdiff/cli.py" || { echo "::error::Missing src/serdiff/cli.py"; exit 1; }
          if git grep -n "pyinstaller/src/serdiff/gui_runner.py" -- . ; then
            echo "::error::Stale path 'pyinstaller/src/serdiff/gui_runner.py' found above. Fix references."
            exit 1
          fi
          echo "Entrypoint scripts OK."

      - name: Build GUI & CLI binaries
        id: package
        shell: bash
        run: |
          set -e
          rm -rf build dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --windowed -n "SER-Diff" src/serdiff/gui_runner.py
            pyinstaller --onefile --console -n "ser-diff" src/serdiff/cli.py

            mkdir -p upload/win
            cp dist/SER-Diff.exe upload/win/
            cp dist/ser-diff.exe upload/win/
            printf "GUI: SER-Diff.exe\nCLI: ser-diff.exe\n" > upload/win/README_RUN_ME.txt
            powershell -command "Compress-Archive -Path upload\\win\\* -DestinationPath SER-Diff-Windows.zip"
            echo "archive=SER-Diff-Windows.zip" >> "$GITHUB_OUTPUT"

          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --onefile --windowed -n "SER-Diff" src/serdiff/gui_runner.py
            pyinstaller --onefile --console -n "ser-diff" src/serdiff/cli.py

            mkdir -p upload/mac
            cp -R "dist/SER-Diff.app" upload/mac/
            cp "dist/ser-diff" upload/mac/
            printf "GUI: SER-Diff.app (Gatekeeper may prompt)\nCLI: ./ser-diff\n" > upload/mac/README_RUN_ME.txt
            (cd upload/mac && zip -r ../../SER-Diff-macOS.zip .)
            echo "archive=SER-Diff-macOS.zip" >> "$GITHUB_OUTPUT"

          else
            pyinstaller --onefile --windowed -n "ser-diff-gui" src/serdiff/gui_runner.py
            pyinstaller --onefile --console -n "ser-diff" src/serdiff/cli.py

            mkdir -p upload/linux
            cp dist/ser-diff-gui upload/linux/
            cp dist/ser-diff upload/linux/
            printf "GUI: ./ser-diff-gui\nCLI: ./ser-diff\n" > upload/linux/README_RUN_ME.txt
            (cd upload/linux && zip -r ../../SER-Diff-Linux.zip .)
            echo "archive=SER-Diff-Linux.zip" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.archive }}
